# Setup docker compose file for rabbitmq and postgres
#
#
#

version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/rabbitmq/data:/var/lib/rabbitmq
      - ./data/rabbitmq/logs:/var/log/rabbitmq
      - ./data/rabbitmq/mnesia:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCL
      - RABBITMQ_NODENAME=rabbit@rabbitmq

    networks:
      - default


networks:
  default:
    driver: bridge